package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;

@Getter
@Setter
public class League {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEAGUE.LEAGUE_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private String leagueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEAGUE.ID
     *
     * @return the value of PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEAGUE.ID
     *
     * @param id the value for PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEAGUE.LEAGUE_NAME
     *
     * @return the value of PUBLIC.LEAGUE.LEAGUE_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public String getLeagueName() {
        return leagueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEAGUE.LEAGUE_NAME
     *
     * @param leagueName the value for PUBLIC.LEAGUE.LEAGUE_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName;
    }
}