package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.TEAM_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private String teamName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.ID
     *
     * @return the value of PUBLIC.TEAM.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.ID
     *
     * @param id the value for PUBLIC.TEAM.ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.TEAM_NAME
     *
     * @return the value of PUBLIC.TEAM.TEAM_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.TEAM_NAME
     *
     * @param teamName the value for PUBLIC.TEAM.TEAM_NAME
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    private List<Player> players;

    private List<League> leagues;
}