package lt.vu.usecases.mybatis.model;

public class TeamLeague {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_LEAGUE.TEAM_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_LEAGUE.LEAGUE_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    private Integer leagueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_LEAGUE.TEAM_ID
     *
     * @return the value of PUBLIC.TEAM_LEAGUE.TEAM_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_LEAGUE.TEAM_ID
     *
     * @param teamId the value for PUBLIC.TEAM_LEAGUE.TEAM_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_LEAGUE.LEAGUE_ID
     *
     * @return the value of PUBLIC.TEAM_LEAGUE.LEAGUE_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public Integer getLeagueId() {
        return leagueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_LEAGUE.LEAGUE_ID
     *
     * @param leagueId the value for PUBLIC.TEAM_LEAGUE.LEAGUE_ID
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    public void setLeagueId(Integer leagueId) {
        this.leagueId = leagueId;
    }
}