package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.League;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LeagueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LEAGUE
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LEAGUE
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    int insert(League record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LEAGUE
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    League selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LEAGUE
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    List<League> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LEAGUE
     *
     * @mbg.generated Sun Mar 31 14:21:15 EEST 2019
     */
    int updateByPrimaryKey(League record);
}